### PR TITLE
Optional registration link when creating event

### LINKED ISSUE #267: POST na competition/event vyzaduje registration_link
ked to v payloade chyba, alebo dam `null`, dostanem:
```
registration_link: ["Toto pole je povinné."]
```
ked dam do payloadu `registration_link: {}`, dostanem:
```
"registration_link": {
    "url": [
      "Toto pole je povinné."
    ],
    "start": [
      "Toto pole je povinné."
    ],
    "end": [
      "Toto pole je povinné."
    ],
    "additional_info": [
      "Toto pole je povinné."
    ],
    "event": [
      "Toto pole je povinné."
    ]
  },
```

zhodli sme sa, ze event budeme vediet vytvorit bez tohto pola

### PR DESCRIPTION
**Pull request by mmihalik**
closes #267

### CODE REVIEW

**Comment by rtrembecky** [comment]
@mmihalik create event za Webmastera s payloadom `{"id":null,"year":2023,"school_year":"2023/2024","start":"2023-11-01T15:03:00.000Z","end":"2023-11-30T15:04:00.000Z","competition":0,"publication_set":[]}` alebo `{"id":null,"year":2023,"school_year":"2023/2024","start":"2023-11-03T15:08:00.000Z","end":"2023-11-24T15:08:00.000Z","competition":0}` (rozdiel len v `publication_set`) stale hadze 500
image

**Comment by rtrembecky** [comment]
pri explicitnom passe `registration_link: null`:
`{"id":null,"year":2023,"school_year":"2023/2024","start":"2023-11-02T15:35:00.000Z","end":"2023-11-30T15:35:00.000Z","registration_link":null,"competition":0}`

image

**Comment by mmihalik** [comment]
Už fachči podľa mňa

**Review by rtrembecky — APPROVED** [review]
asi aj podla mna

**Pull request merged**
